### PA8, Version 1, Clay Jackson, CS-150 Spring 2023

In [1]:
import numpy as np

In [2]:
# #1
A=np.array([[10,20],[30,40]])

In [4]:
Squared=A**2

print(Squared)

[[ 100  400]
 [ 900 1600]]


In [5]:
Add=A+100
print(Add)

[[110 120]
 [130 140]]


In [6]:
Multiply=A*5
print(Multiply)

[[ 50 100]
 [150 200]]


In [8]:
Square_Root=np.sqrt(A)
print(Square_Root)

[[3.16227766 4.47213595]
 [5.47722558 6.32455532]]


In [9]:
# #2
A1=np.array([[3,6,9], [12,15,18], [21,24,27]])
print(A1)

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [10]:
A2=np.linspace(10,20,9).reshape(3,3)
print(A2)

[[10.   11.25 12.5 ]
 [13.75 15.   16.25]
 [17.5  18.75 20.  ]]


In [11]:
Multiplied_Array=A1*A2
print(Multiplied_Array)

[[ 30.   67.5 112.5]
 [165.  225.  292.5]
 [367.5 450.  540. ]]


In [16]:
# #3

process1=np.load('process1.npy')
process2=np.load('process2.npy')
process3=np.load('process3.npy')
process4=np.load('process4.npy')
process5=np.load('process5.npy')

In [19]:
My_dataset=np.stack([process1,process2,process3,process4,process5])
print(My_dataset)

[[[52 12 81  0 58]]

 [[96  4 61 16 43]]

 [[38 96 45 17 58]]

 [[97 21 22 25  6]]

 [[77  6 19  2 74]]]


In [20]:
Mean=np.mean(My_dataset, axis=0)
print(Mean)

[[72.  27.8 45.6 12.  47.8]]
